name: BullsEye
description: My First Flutter App

dependencies:
    flutter:
        sdk: flutter
dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - images/